return {}
-- return {
--   "nvim-neo-tree/neo-tree.nvim",
--   branch = "v3.x",
--   dependencies = {
--     "nvim-lua/plenary.nvim",
--     "MunifTanjim/nui.nvim",
--     "nvim-tree/nvim-web-devicons", -- optional, but recommended
--   },
--   opts = {
--     filesystem = {
--       follow_current_file = {
--         enabled = true,
--       },
--       filtered_items = {
--         hide_dotfiles = false, -- показывать .файлы
--         hide_gitignored = false, -- показывать gitignored
--       },
--     },
--     event_handlers = {
--       {
--         event = "file_open_requested",
--         handler = function()
--           require("neo-tree.command").execute({ action = "close" })
--         end,
--       },
--     },
--   },
-- }
